description: Services configuration section.
type: object
properties:
  dhcp-server:
    $ref: https://ucentral.io/schema/v1/service/dhcp-server/
  dhcp-relay:
    $ref: https://ucentral.io/schema/v1/service/dhcp-relay/
  dns:
    $ref: https://ucentral.io/schema/v1/service/dns/
  ntp:
    $ref: https://ucentral.io/schema/v1/service/ntp/
  lldp:
    $ref: https://ucentral.io/schema/v1/service/lldp/
  mdns:
    $ref: https://ucentral.io/schema/v1/service/mdns/
  pppoe-server:
    $ref: https://ucentral.io/schema/v1/service/pppoe-server/
  web-proxy:
    $ref: https://ucentral.io/schema/v1/service/web-proxy/
  tftp-server:
    $ref: https://ucentral.io/schema/v1/service/tftp-server/
  igmp-proxy:
    $ref: https://ucentral.io/schema/v1/service/igmp-proxy/
  snmp:
    $ref: https://ucentral.io/schema/v1/service/snmpv3/
