description: Services configuration section.
type: object
properties:
  dhcp-server:
    $ref: https://ucentral.io/schema/v1/service/dhcp-server/
  dhcp-relay:
    $ref: https://ucentral.io/schema/v1/service/dhcp-relay/
  dns:
    $ref: https://ucentral.io/schema/v1/service/dns/
  ntp:
    $ref: https://ucentral.io/schema/v1/service/ntp/
  lldp:
    $ref: https://ucentral.io/schema/v1/service/lldp/
  mdns:
    $ref: https://ucentral.io/schema/v1/service/mdns/
  pppoe-server:
    $ref: https://ucentral.io/schema/v1/service/pppoe-server/
  web-proxy:
    $ref: https://ucentral.io/schema/v1/service/web-proxy/
  tftp-server:
    $ref: https://ucentral.io/schema/v1/service/tftp-server/
  igmp-proxy:
    $ref: https://ucentral.io/schema/v1/service/igmp-proxy/
  traffic-policy:
    $ref: https://ucentral.io/schema/v1/service/traffic-policy/
  snmp:
    $ref: https://ucentral.io/schema/v1/service/snmpv3/
  syslog:
    $ref: https://ucentral.io/schema/v1/service/syslog/
  netflow:
    $ref: https://ucentral.io/schema/v1/service/netflow/
  sflow:
    $ref: https://ucentral.io/schema/v1/service/sflow/
